// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // --conditions=react-server: the seed script imports "server-only"
    // (transitively, via src/server/db/admin-client.ts) — Next sets this
    // Node export condition automatically inside its RSC bundle, but a
    // standalone tsx/node process needs it passed explicitly, or
    // server-only's package.json "exports" map resolves to its always-
    // throws browser/default branch. Same fix as vitest.config.mts's unit
    // project.
    seed: "tsx --conditions=react-server prisma/seed/index.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
